### ISSUE TITLE
Guard on edges of map crashes game

### ISSUE THREAD

**Issue by mickyscreggs** [MicrowavedScrambledEggs/SWEN222_GroupPage_ArtGame#10]
@kaishuoy  Floor.checkGuard() throws array index out of bounds exceptions. Maybe it's trying to check for something out side of the map? Happens when guard 6 gets to row 14 col 0

**Comment by kaishuoy** [comment]
this is really weird because the only time this should happen is if you dont close off the game world ie no wall on west side of tile at r14,c0. the method was designed with this in mind

anyway ive added another check for out of bounds, should fix the problem now. can you have a look at that tile see if walls are ok?
