### ISSUE TITLE
Player sprite needs a direction

### ISSUE THREAD

**Issue by kaishuoy** [MicrowavedScrambledEggs/SWEN222_GroupPage_ArtGame#8]
@mootshell reckon you can do this? noticed while using the 3d gui version today that it was hard to test/play cos you cant see which way the guy is facing and all actions require player to be facing the object

**Comment by mootshell** [comment]
I was planning on eventually extending the sprite class for the purpose of players and guards so that their texture is chosen based off their current animation frame and their orientation with respect to the camera. This is slightly lower on my priority list at the moment (I need to fix the spritesheet bug before this is possible, and it also requires a bit more pixel art, which I'll take care of tomorrow), but I can push it up if you need it sooner? :)

**Comment by mickyscreggs** [comment]
Yeah agree with @mootshell, low priority. Stuff like doors, being able to distinguish walls from floors and a sprite for guards (even if it's just for one direction for now) are probably more urgent

**Comment by kaishuoy** [comment]
yea all good not a huge deal. just a minor thing i thought about earlier
